version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: miBD
            MYSQL_USER: alumno
            MYSQL_PASSWORD: alumno
            MYSQL_ROOT_PASSWORD: secreta
        volumes:
            - ./script-sql:/docker-entrypoint-initdb.d
            - persistente:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: alumno
            MYSQL_PASSWORD: alumno
            MYSQL_ROOT_PASSWORD: secreta 
volumes:
    persistente:
